server:
  port: 8005
spring:
  thymeleaf:
    #禁用模板缓存
    cache: false
  redis:
    host: 192.168.188.146
    port: 6379
  session:
    store-type: redis #session存储方式
    timeout: 1800     #session过期时间 单位：秒

